- name: Deployment de un sitio estatico
  hosts: all
  become: yes
  pre_tasks:
    - name: Verificar si el OS es Ubuntu
      set_fact:
        is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
  vars_files:
    - "vars/{{ env_name }}.yml"
  tasks:
    - name: Instalar servicio Apache
      include_tasks: includes/install-apache2.yml

    - name: crear directorio para el sitio
      file:
        path: "{{ site_dir }}"
        state: directory
        owner: www-data
        group: www-data
      when: is_ubuntu

    - name: copiar index.html al directorio del sitio
      copy:
        src: files/index.html
        dest: "{{ site_dir }}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'
      when: is_ubuntu

    - name: Configuracion del sitio apache
      template:
        src: templates/ansible_site.conf.j2
        dest: "/etc/apache2/sites-available/{{ env_name }}_ansible_site.conf"
      notify:
        - Reload Apache
      when: is_ubuntu

    - name: Activa el nuevo sitio
      command: "a2ensite {{ env_name }}_ansible_site.conf"
      notify:
        - Reload Apache
      when: is_ubuntu

    - name: Deshabilita el sitio default
      command: a2dissite 000-default.conf
      notify:
        - Reload Apache
      when: is_ubuntu

    - name: Asegurarse que apache escuche en el puerto correspondiente
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: "^Listen {{ apache_port }}$"
        line: "Listen {{ apache_port }}"
        insertafter: "^Listen 80$"
      notify:
        - Reload Apache
      when: is_ubuntu

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
      when: is_ubuntu
